config/routes.rb
Rails.application.routes.draw do



  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :evenements
  resources :participants
  resources :pages

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/index'  => 'pages#index'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  get '/signout' => 'sessions#destroy'



  get 'mycity'   => 'pages#myCity'


  get '/around'   => 'pages#myCity'
  get '/myEvents' => 'evenements#show_my_events'
  get '/allEvents' => 'evenements#show_all_events'
  get '/addEvent' => 'evenements#new'


  get 'users/show'
  get 'users/new'

  get 'evenements/show'
  get 'evenements/admis'


  get 'sessions/new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evenement.rb
class Evenement < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
  validates :latitude, :presence   =>true
  validates :longitude, :presence  =>true
  validates :datee,     :presence      =>true

  # Note that if you used attr_accessible, and all other fields cannot be assigned through User.new(params[:user[), while if you used attr_protected, only those fields cannot assigned.
  def self.search(search)
    where("lower (route)  ILIKE ? OR lower(ville) ILIKE ? or lower(address) ILIKE ? or lower(pays) ILIKE ?", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")
  end


end

app/models/page.rb
class Page < ActiveRecord::Base


end

app/models/participant.rb
class Participant < ApplicationRecord

  validates :userId,     :uniqueness      => { :scope => :evenementId }



end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base



  attr_accessor :password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  #Nom
  validates :nom, :presence   =>true,
                   :length     =>{maximum: 50}
  before_save{email.downcase!}
  #Email
  validates :email, :presence  =>true,
                    :length    =>{:maximum => 255},
                    :format    =>{:with    => VALID_EMAIL_REGEX},
                    :uniqueness=>{:case_sensitive => false }
  #Password
  validates :password, :presence     => true,
            :confirmation => true,
            :length       => { :within => 6..40 }



  before_save :encrypt_password

  def has_password?(password_soumis)
    encrypted_password == encrypt(password_soumis)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/evenements_controller.rb
class EvenementsController < ApplicationController
  require 'securerandom'
  require 'date'



  def show_all_events
    @events = Evenement.all
    @efirst = Evenement.first
  end

  def show_my_events
    @events = Evenement.all
  end

  def show
    @eactual    = Evenement.find(params[:id])
    @createur   = User.find(@eactual.userId).nom
    @pwd        = params[:verifpass]
    @ebool      = false
    if !@eactual.isPrivate || @eactual.userId==current_user.id
      @ebool=true
    end


    @participant   = Participant.where(status: 'participe', evenementId: @eactual.id)
    @noparticipant = Participant.where(status: 'refus'    , evenementId: @eactual.id)
    @mbparticipant = Participant.where(status: '?'        , evenementId: @eactual.id)

    @tabtel = Array.new
    @tabmel = Array.new
    @participant.each do |p|
      @tabtel << User.find(p.userId).tel
      @tabmel << User.find(p.userId).email
    end




    @listtel=""
    @listmel=""
    @tabtel.each do |t|
      @listtel.concat(t.to_s + ",")
    end
    @listtel.concat("")

    @tabmel.each do |m|
      @listmel.concat(m.to_s + ",")
    end

  end




  def new
    @evenement = Evenement.new
    @title = "Nouvel evenement"


  end


  def create
    @evenement = Evenement.new
    @evenement.numero     = params[:evenement][:numero]
    @evenement.route      = params[:evenement][:route]
    @evenement.zipCode    = params[:evenement][:zipCode]
    @evenement.ville      = params[:evenement][:ville]
    @evenement.pays       = params[:evenement][:pays]
    @evenement.address    = @evenement.numero.to_s + " " + @evenement.route.to_s + " " + @evenement.ville.to_s + " " + @evenement.zipCode.to_s


    @elonlat = Geocoder.search(@evenement.address)
    @evenement.longitude  = @elonlat[0].longitude
    @evenement.latitude   = @elonlat[0].latitude
    @evenement.isPrivate  = params[:evenement][:isPrivate]
    @evenement.datee      = params[:evenement][:datee]
    @evenement.userId     = current_user.id


    if @evenement.isPrivate
      @evenement.pwd = SecureRandom.hex(6)


    end
    if @evenement.save
      puts "Reussite"
      if @evenement.isPrivate
        EventMailer.pwdevent_email(@evenement,current_user).deliver_now
      end
      redirect_to @evenement
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def myCity
    @events = Evenement.all
    location =   request.remote_ip
    @latV = request.location.latitude
    @logV = request.location.longitude

  end

  def index
    @evenements = Evenement.all
    if params[:search]
      @events = Evenement.search(params[:search]).order("created_at DESC")
    else
      @events = ""
    end

  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def show

  end

  def new
    @participant = Participant.new
    @title = "S'inscrire"

  end

  def create
    @participant = Participant.new
    @participant.evenementId   = params[:evenementId]
    @participant.userId        = current_user.id
    @participant.status        = params[:status]

    @participant.save

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @titre = "S'identifier"
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Combinaison Email/Mot de passe invalide."
      @titre = "S'identifier"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate, :only => [:edit, :update]
  before_action :correct_user, :only => [:edit, :update]

  def show
    @user = User.find(params[:id])
    @img_user = Gravatar.new(@user.email).image_url
  end

  def new
    @user = User.new
    @title = "S'inscrire"
  end

  def create
    @user = User.new
    @user.nom                   = params[:user][:nom]
    @user.email                 = params[:user][:email]
    @user.password              = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.tel                   = params[:user][:tel]

    if @user.save
      sign_in @user
      UserMailer.welcome_email(@user).deliver_now
      redirect_to @user
    else
      @titre = "Inscription"
      render 'new'
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evenements_helper.rb
module EvenementsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

  def current_user?(user)
    user == current_user
  end


end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/evenements/new.html.erb
<h1>Evenements#new</h1>
<!--@ERROR : ne pas laisser ça ici | AutoCompletition folder => app/assets/javascripts/ -->


<script type="text/javascript">


// Lie le champs adresse en champs autocomplete afin que l'API puisse afficher les propositions d'adresses
function initializeAutocomplete(id) {
var element = document.getElementById(id);
if (element) {
var autocomplete = new google.maps.places.Autocomplete(element, {types: ['geocode']});
google.maps.event.addListener(autocomplete, 'place_changed', onPlaceChanged);
}

}


// Injecte les données dans les champs du formulaire lorsqu'une adresse est sélectionnée
function onPlaceChanged() {
var place = this.getPlace();

for (var i in place.address_components) {
var component = place.address_components[i];
for (var j in component.types) {
var type_element = document.getElementById(component.types[j]);
if (type_element) {
type_element.value = component.long_name;
}
}
}

var longitude = document.getElementById("longitude");
var latitude = document.getElementById("latitude");
longitude.value = place.geometry.location.lng();
latitude.value = place.geometry.location.lat();

}

// Initialisation du champs autocomplete
google.maps.event.addDomListener(window, 'load', function() {
initializeAutocomplete('user_input_autocomplete_address');
});
</script>

<script async defer
  src=" https://maps.googleapis.com/maps/api/js?libraries=places&amp;key=AIzaSyBec10Y1_D_kZvAzf6QI60NHQsAJvSUNR0">
</script>





<div class="col-lg-12">
<div id="addE" onmouseover="initializeAutocomplete('user_input_autocomplete_address')"> <!--touchenter-->
<%= form_for(@evenement) do |f| %>

    <div class="form-group col-lg-12">
      <%= f.label :adresse, "Adresse" %><br />
      <%= f.text_field :adresse, :id => "user_input_autocomplete_address", :placeholder => "Adresse du lieu" , :class => "col-lg-12"  %>
    </div>
      <p>Ou remplissez ces champs : </p>
    <div class="form-group">
      <%= f.label :numero, "Numéro" %><br />
      <%= f.text_field :numero, :id => "street_number"%>
    </div>
    <div class="form-group">
      <%= f.label :route, "Nom de la rue" %><br />
      <%= f.text_field :route, :id => "route"%>
    </div>
    <div class="form-group">
      <%= f.label :zipCode , "Code postal" %><br />
      <%= f.text_field :zipCode, :id => "postal_code"%>
    </div>
    <div class="form-group">
      <%= f.label :ville, "Ville" %><br />
      <%= f.text_field :ville, :id => "locality"%>
    </div>
    <div class="form-group">
      <%= f.label :pays, "Pays" %><br />
      <%= f.text_field :pays, :id => "country"%>
    </div>
    <hr>
    <div class="form-group">
      <%= f.label :latitude, "Latitude" %><br />
      <%= f.text_field :latitude, :id => "latitude", :readonly => true%>
    </div>
    <div class="form-group">
      <%= f.label :longitude, "Longitude" %><br />
      <%= f.text_field :longitude, :id => "longitude", :readonly => true%>
    </div>
      <div class="form-group">
        <%= f.label :datee, "Date" %><br />
        <%= f.text_field :datee, :id => "datepicker1", :data => {:provide => 'datepicker','date-format' => 'dd-mm-yyyy', 'date-autoclose' => 'true'} %>
      </div>

    <div class="form-group">
      <%= f.label :isPrivate,"L'évenement est privé" %>
      <%= f.check_box :isPrivate %>
    </div>



    <div class="actions">
      <%= f.submit "Ajouter" %>
    </div>
<% end %>




</div>

</div>

app/views/evenements/show.erb
<script type="text/javascript">
  var map;
  function initMap() {
    var mapOptions = {
      center: {lat: <%= @eactual.latitude %>, lng: <%= @eactual.longitude %>},
      zoom: 15
    };

    map = new google.maps.Map(document.getElementById('map'), mapOptions);

    addMarker(<%= @eactual.latitude %>, <%= @eactual.longitude %> );


    function addMarker(lat, lng) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat, lng),
        map: map,
        title: 'foo'
      });
    }

  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBec10Y1_D_kZvAzf6QI60NHQsAJvSUNR0&callback=initMap">
</script>


<%if @ebool==false%>

    <%=form_tag url_for(:controller => 'evenements', :action => 'show'), :method => 'get' do %>
        <%= label_tag "Clef de l'événement : "%>
        <%= text_field_tag :verifpass %>
        <%= submit_tag "Envoyer" %>
    <% end %>

    <%if @pwd==@eactual.pwd%>
        <%@ebool=true%>
    <%end%>
<%end%>

<%if @ebool%>
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-6 text-center">
                  <div>Créé par : </div>
                  <div><%= @createur.upcase %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 ">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-12 text-center">
                  <div>Lieu : </div>
                  <div><%= @eactual.address%></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 ">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-3">
                  <i class="fa fa-comments fa-5x"></i>
                </div>
                <div class="col-xs-6 text-center">
                  <div>Date :</div>
                  <div><%= @eactual.datee.strftime("%d-%m-%Y") %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>






      <div class="row ">
        <div class="col-lg-4">
          <%= form_for :participant, :url  => { :controller => "participants", :action => "create", :evenementId => @eactual.id, :status => "participe" } do |f| %>
              <div class="form-group">
                <%= f.button :class => "btn btn-block btn-primary" do%>
                    <i class="glyphicon glyphicon-ok-sign"></i> Je participe
                <%end%>
              </div>
          <%end%>

        </div>
        <div class="col-lg-4">
          <%= form_for :participant, :url  => { :controller => "participants", :action => "create", :evenementId => @eactual.id, :status => "refus" } do |f| %>
              <div class="form-group">
                <%= f.button :class => "btn btn-block btn-primary" do%>
                    <i class="glyphicon glyphicon-remove-sign"></i> Je ne participe pas
                <%end%>
              </div>
          <%end%>

        </div>
      <div class="col-lg-4">
        <%= form_for :participant, :url  => { :controller => "participants", :action => "create", :evenementId => @eactual.id, :status => "?" } do |f| %>
            <div class="form-group">
              <%= f.button :class => "btn btn-block btn-primary" do%>
                  <i class="glyphicon glyphicon-question-sign"></i> Je ne sais pas
              <%end%>
            </div>
        <%end%>
      </div>



    </div>

      <div class="col-xs-12 col-centered">
        <div id="map"></div>
      </div>





      <div class="row">
        <div class="col-lg-4">
          List
        </div>

        <div class="col-lg-4">
          Donut
        </div>

        <div class="col-lg-4">
          Note
        </div>
    </div>


      <div class="row ">

        <!-- Participants  -->
        <div class="col-lg-4">
          <h2>Participants</h2>
          <table class="table center-block">
            <thead>
            <tr>
              <th>Invités </th>
              <th>Statut  </th>
            </tr>
            </thead>
            <tbody>
            <%@participant.each do |p| %>
              <tr>
                <td><%= User.find(p.userId).nom %></td>
                <td><i class="glyphicon glyphicon-ok-sign "></i></td>
              </tr>
            <% end%>
            </tbody>
          </table>
        </div>

        <!-- Refus  -->
        <div class="col-lg-4">
          <h2>Refus</h2>
          <table class="table center-block">
            <thead>
            <tr>
              <th>Invités </th>
              <th>Statut  </th>
            </tr>
            </thead>
            <tbody>
            <%@noparticipant.each do |p| %>
                <tr>
                  <td><%= User.find(p.userId).nom %></td>
                  <td><i class="glyphicon glyphicon-remove-sign "></i></td>
                </tr>
            <% end%>
            </tbody>
          </table>
        </div>


        <!-- Ne sais pas  -->
        <div class="col-lg-4">
          <h2>Indécis  </h2>
          <table class="table center-block">
            <thead>
            <tr>
              <th>Invités </th>
              <th>Statut  </th>
            </tr>
            </thead>
            <tbody>
            <%@mbparticipant.each do |p| %>
                <tr>
                  <td><%= User.find(p.userId).nom %></td>
                  <td><i class="glyphicon glyphicon-question-sign "></i></td>
                </tr>
            <% end%>
            </tbody>
          </table>
        </div>

      </div>

    </div>







    <div class="col-xs-12 col-centered">
      <div id="envoieMsg">
      </div>
      </div>
    </div>

    <!-- /.row -->

  <script type="text/javascript">
      if (screen.width <= 850)
      {
        document.getElementById('envoieMsg').innerHTML = "<a href=\"smsto:<%=@listtel%>?body=Vous êtes participant à l'événement de : <%=@createur%> .  RDV le <%=@eactual.datee%> au <%=@eactual.address%> \">Clique ici pour envoyer un sms aux participants</a>";
      }
      else
      {
        document.getElementById('envoieMsg').innerHTML = "<a href=\"mailto:<%=@listmel%>?subject=Evenement prévu&body=Vous êtes participant à l'événement de : <%=@createur%> .  RDV le <%=@eactual.datee%> au <%=@eactual.address%> \">Clique ici pour envoyer un e-mail aux participants </a>";
      }
  </script>



    <div class="col-xs-12 col-centered">
      <div id="chat">
        chat
      </div>
    </div>
    </div>
<%end%>

app/views/evenements/show_all_events.html.erb
  <div class="col-xs-6 col-centered">
    <div id="map"></div>
  </div>

  <input name="loc" class="col-xs-4 row-centered" type="text"  placeholder="Location">

  <div class="list-group col-xs-5 col-centered" style="overflow: hidden" >
    <% @events.each do |event| %>
        <% if !event.isPrivate %>
            <%= link_to event , class: "list-group-item" do %>
                <span class="glyphicon glyphicon-map-marker"></span>
                <%=event.address%>
            <%end%>
        <% end %>
    <% end %>

  </div>





<script type="text/javascript">
  var map;
  function initMap() {
    var mapOptions = {
      center: {lat:47, lng: 1.8},
      zoom: 6
    };

    map = new google.maps.Map(document.getElementById('map'), mapOptions);

    <% @events.each do |event| %>
    addMarker(<%= event.latitude %>, <%= event.longitude %> );
    <% end %>


    function addMarker(lat, lng) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat, lng),
        map: map,
        title: 'foo'
      });
    }

  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBec10Y1_D_kZvAzf6QI60NHQsAJvSUNR0&callback=initMap">
</script>

app/views/evenements/show_my_events.html.erb
  <h1>Mes événements</h1>
  <div class="list-group col-xs-offset-3"  >
    <% @events.each do |event| %>
            <% if event.userId == current_user.id %>
                <%= link_to event, class: "list-group-item col-xs-8" do %>
                <span class="glyphicon glyphicon-map-marker"></span>
                <% if event.isPrivate %>
                  <%= "[PRIVATE]"%>
                <% end %>
                <%=event.numero.to_s + " " + event.route + " - " + event.ville %>
            <%end%>
        <% end %>
    <% end %>
  </div>

app/views/layouts/_header.html.erb
<header>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>TheHappyEvent</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- AutoCompletition pour google places -->

  </head>
  <body>
  <div class="container">
    <%= render 'layouts/header' %>
    <%= render 'shared/navigation' %>

  </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class=" jumbotron text-center">
  <h1>The Happy Event</h1><br>
  <h2>Organisez vos événements privés ou publics et découvrez ce qui se prépare autour de vous !  </h2>
  <div class="container">
    <%= form_tag(pages_path, :method => "get", id: "search-form" ) do %>
        <%= text_field_tag :search, params[:search], placeholder: "Rechercher une ville, une adresse, un pays...",class: "col-md-10 col-xs-12 row-centered" %>
        <%= submit_tag "Rechercher" , class: "col-lg-2 col-xs-12 row-centered"%>
    <% end %>
    <div class="recherche col-lg-12 col-xs-12 ">
    <% if @events.present? %>
        <% @events.each do |e| %>
            <% if !e.isPrivate  %>
              <%=  link_to e , class: "list-group-item" do %>
                  <span class="glyphicon glyphicon-map-marker"></span>
                  <%=e.address %>
              <%end%>
            <%end%>

    <%end%>

    <% else %>
        <p>Aucun résultat pour : <%= params[:search] %>.</p>
    <% end %>
    <%= link_to 'allEvents' , class: "btn btn-block btn-primary" do %>
        <i class="glyphicon glyphicon-chevron-down"></i>
        <%="Voir la carte des événements"%>
    <% end %>
    </div>

  </div>
</div>








<br>
<div class="col-lg-7 ">
  <div id="map"></div>
</div>




<div class="list-group col-lg-5 col-centered" >
  <% @evenements.each do |event| %>
      <% if !event.isPrivate %>
          <%= link_to event , class: "list-group-item" do %>
              <span class="glyphicon glyphicon-map-marker"></span>
              <%=event.address %>
          <%end%>
      <% end %>
  <% end %>

</div>
</div>

<script type="text/javascript">
  var map;
  function initMap()
  {
    var mapOptions = {
      center: {lat: 47, lng: 1.8},
      zoom: 6

    };

    map = new google.maps.Map(document.getElementById('map'), mapOptions);

    <% @evenements.each do |event| %>
      <%if !event.isPrivate %>
        addMarker(<%= event.latitude %>, <%= event.longitude %> );
      <% end %>
    <% end %>

    function addMarker(lat, lng) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat, lng),
        map: map,
        title: 'foo'
      });
    }

  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBec10Y1_D_kZvAzf6QI60NHQsAJvSUNR0&callback=initMap">
</script>

app/views/pages/messagerie.html.erb
<h1>Messagerie</h1>

app/views/pages/myCity.html.erb
<div class="col-xs-12 ">
  <div id="map"></div>
</div>

<script type="text/javascript">
  var map;
  function initMap()
  {
    var mapOptions = {
      center: {lat: <%=@latV%>, lng: <%=@logV%>},
      zoom: 11

    };

    map = new google.maps.Map(document.getElementById('map'), mapOptions);



    function addMarker(lat, lng) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(lat, lng),
        map: map,
        title: 'foo'
      });
    }

  }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBec10Y1_D_kZvAzf6QI60NHQsAJvSUNR0&callback=initMap">
</script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "erreur") %>
        ont empêché d'enregistrer votre inscription</h2>
      <p>Merci de corriger ces champs :</p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_navigation.html.erb
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-left">
        <li > <%= link_to "Accueil", index_path %></li>
        <% if signed_in? %>
            <li >               <%= link_to "Mes événements", myEvents_path %>  </li>
            <li >               <%= link_to "Tout les événements", allEvents_path %>  </li>

            <li >               <%= link_to "Autour de moi", around_path %>  </li>
            <li >               <%= link_to "Thermographie"  %>  </li>


            <li >               <%= link_to "Mon compte", current_user %>  </li>
            <li >               <%= link_to "Déconnexion", signout_path %> </li>

            <!--<li role="presentation">               <a <\%= link_to "Editer", edition_path(current_user) %></a></li>-->

        <% else %>
            <li >               <%= link_to "S'identifier", signin_path %></li>
            <li >               <%= link_to "S'inscrire", signup_path %></li>

        <% end %>
      </ul>

    </div><!--/.nav-collapse -->

  </div><!--/.navbar -->

app/views/users/edit.html.erb
<h1>Edition du profil</h1>

<%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="field">
      <%= f.label :name, "Nom" %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email, "Email" %><br />
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password, "Mot de passe" %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirmation mot de passe", "Confirmation" %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
<% end %>

<div>
  <a href="http://gravatar.com/emails">Changer</a>
</div>